/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AttackLabRouteImport } from './routes/attack-lab'
import { Route as DefenderRouteImport } from './routes/defender'
import { Route as HealthRouteImport } from './routes/health'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AttackLabRoute = AttackLabRouteImport.update({
  id: '/attack-lab',
  path: '/attack-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const DefenderRoute = DefenderRouteImport.update({
  id: '/defender',
  path: '/defender',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/attack-lab': typeof AttackLabRoute
  '/defender': typeof DefenderRoute
  '/health': typeof HealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/attack-lab': typeof AttackLabRoute
  '/defender': typeof DefenderRoute
  '/health': typeof HealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/attack-lab': typeof AttackLabRoute
  '/defender': typeof DefenderRoute
  '/health': typeof HealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/assistant' | '/attack-lab' | '/defender' | '/health'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/assistant' | '/attack-lab' | '/defender' | '/health'
  id: '__root__' | '/' | '/assistant' | '/attack-lab' | '/defender' | '/health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  AttackLabRoute: typeof AttackLabRoute
  DefenderRoute: typeof DefenderRoute
  HealthRoute: typeof HealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attack-lab': {
      id: '/attack-lab'
      path: '/attack-lab'
      fullPath: '/attack-lab'
      preLoaderRoute: typeof AttackLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/defender': {
      id: '/defender'
      path: '/defender'
      fullPath: '/defender'
      preLoaderRoute: typeof DefenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  AttackLabRoute: AttackLabRoute,
  DefenderRoute: DefenderRoute,
  HealthRoute: HealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
